In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer

In [2]:
breast_cancer = load_breast_cancer()

In [3]:
data = pd.DataFrame(breast_cancer.data, columns=breast_cancer.feature_names)

In [4]:
data.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [5]:
data.describe()

mean radius  mean texture  mean perimeter    mean area  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       mean smoothness  mean compactness  mean concavity  mean concave points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       mean symmetry  mean fractal dimension  ...  worst radius  \
count     569.000000              569.000000  ...    569.000000   
mean        0.181162                0.062798  ...     16.269190   
std         0.027414                0.007060  ...      4.833242   
min         0.106000                0.049960  ...      7.930000   
25%         0.161900                0.057700  ...     13.010000   
50%         0.179200                0.061540  ...     14.970000   
75%         0.195700                0.066120  ...     18.790000   
max         0.304000                0.097440  ...     36.040000   

       worst texture  worst perimeter   worst area  worst smoothness  \
count     569.000000       569.000000   569.000000        569.000000   
mean       25.677223       107.261213   880.583128          0.132369   
std         6.146258        33.602542   569.356993          0.022832   
min        12.020000        50.410000   185.200000          0.071170   
25%        21.080000        84.110000   515.300000          0.116600   
50%        25.410000        97.660000   686.500000          0.131300   
75%        29.720000       125.400000  1084.000000          0.146000   
max        49.540000       251.200000  4254.000000          0.222600   

       worst compactness  worst concavity  worst concave points  \
count         569.000000       569.000000            569.000000   
mean            0.254265         0.272188              0.114606   
std             0.157336         0.208624              0.065732   
min             0.027290         0.000000              0.000000   
25%             0.147200         0.114500              0.064930   
50%             0.211900         0.226700              0.099930   
75%             0.339100         0.382900              0.161400   
max             1.058000         1.252000              0.291000   

       worst symmetry  worst fractal dimension  
count      569.000000               569.000000  
mean         0.290076                 0.083946  
std          0.061867                 0.018061  
min          0.156500                 0.055040  
25%          0.250400                 0.071460  
50%          0.282200                 0.080040  
75%          0.317900                 0.092080  
max          0.663800                 0.207500  

[8 rows x 30 columns]

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [7]:
data.describe()

mean radius  mean texture  mean perimeter    mean area  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       mean smoothness  mean compactness  mean concavity  mean concave points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       mean symmetry  mean fractal dimension  ...  worst radius  \
count     569.000000              569.000000  ...    569.000000   
mean        0.181162                0.062798  ...     16.269190   
std         0.027414                0.007060  ...      4.833242   
min         0.106000                0.049960  ...      7.930000   
25%         0.161900                0.057700  ...     13.010000   
50%         0.179200                0.061540  ...     14.970000   
75%         0.195700                0.066120  ...     18.790000   
max         0.304000                0.097440  ...     36.040000   

       worst texture  worst perimeter   worst area  worst smoothness  \
count     569.000000       569.000000   569.000000        569.000000   
mean       25.677223       107.261213   880.583128          0.132369   
std         6.146258        33.602542   569.356993          0.022832   
min        12.020000        50.410000   185.200000          0.071170   
25%        21.080000        84.110000   515.300000          0.116600   
50%        25.410000        97.660000   686.500000          0.131300   
75%        29.720000       125.400000  1084.000000          0.146000   
max        49.540000       251.200000  4254.000000          0.222600   

       worst compactness  worst concavity  worst concave points  \
count         569.000000       569.000000            569.000000   
mean            0.254265         0.272188              0.114606   
std             0.157336         0.208624              0.065732   
min             0.027290         0.000000              0.000000   
25%             0.147200         0.114500              0.064930   
50%             0.211900         0.226700              0.099930   
75%             0.339100         0.382900              0.161400   
max             1.058000         1.252000              0.291000   

       worst symmetry  worst fractal dimension  
count      569.000000               569.000000  
mean         0.290076                 0.083946  
std          0.061867                 0.018061  
min          0.156500                 0.055040  
25%          0.250400                 0.071460  
50%          0.282200                 0.080040  
75%          0.317900                 0.092080  
max          0.663800                 0.207500  

[8 rows x 30 columns]

In [8]:
X = breast_cancer.data
y = breast_cancer.target

In [9]:
print(X.shape)
print(y.shape)

(569, 30)
(569,)


In [10]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [11]:
print(X)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

In [13]:
X = np.asarray(X)
y = np.asarray(y)

In [14]:
from sklearn.svm import SVC
model = SVC()

In [15]:

para = {
    'C':[ 0.1, 1,10,100],
    'kernel': ['linear', 'poly', 'rbf', 'sigmoid']
}


In [16]:
clf =  GridSearchCV(model, para,cv=5)

In [17]:
clf.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [18]:
clf.cv_results_

{'mean_fit_time': array([3.21035671e-01, 1.35876656e-02, 2.16067791e-02, 3.66410732e-02,
        4.04046202e+00, 3.84063721e-03, 4.67696190e-03, 1.47459507e-02,
        4.71982827e+00, 4.13770676e-03, 4.04963493e-03, 1.41399384e-02,
        1.16867478e+01, 7.45391846e-03, 7.02314377e-03, 4.21021938e-02]),
 'std_fit_time': array([2.50600889e-01, 8.32555952e-03, 7.82841927e-03, 1.69102696e-02,
        2.39099403e+00, 1.44113837e-04, 9.35909513e-05, 5.42187564e-04,
        9.79701445e-01, 1.65883924e-04, 1.03770612e-04, 1.02119534e-03,
        3.64122043e+00, 1.49787562e-03, 4.16038259e-04, 2.26076878e-02]),
 'mean_score_time': array([0.00277805, 0.00521998, 0.00864949, 0.01057472, 0.00258121,
        0.001437  , 0.0020514 , 0.00411515, 0.00140319, 0.00131574,
        0.00170465, 0.00382147, 0.00139656, 0.00193329, 0.00264182,
        0.00752368]),
 'std_score_time': array([1.08618566e-03, 3.29391757e-03, 3.06021709e-03, 6.01486305e-03,
        1.20834501e-03, 7.83673419e-05, 6.87253537e-

In [19]:
clf.best_params_

{'C': 100, 'kernel': 'linear'}

In [20]:
clf.best_score_

np.float64(0.9631268436578171)

In [21]:
clf.cv_results_

{'mean_fit_time': array([3.21035671e-01, 1.35876656e-02, 2.16067791e-02, 3.66410732e-02,
        4.04046202e+00, 3.84063721e-03, 4.67696190e-03, 1.47459507e-02,
        4.71982827e+00, 4.13770676e-03, 4.04963493e-03, 1.41399384e-02,
        1.16867478e+01, 7.45391846e-03, 7.02314377e-03, 4.21021938e-02]),
 'std_fit_time': array([2.50600889e-01, 8.32555952e-03, 7.82841927e-03, 1.69102696e-02,
        2.39099403e+00, 1.44113837e-04, 9.35909513e-05, 5.42187564e-04,
        9.79701445e-01, 1.65883924e-04, 1.03770612e-04, 1.02119534e-03,
        3.64122043e+00, 1.49787562e-03, 4.16038259e-04, 2.26076878e-02]),
 'mean_score_time': array([0.00277805, 0.00521998, 0.00864949, 0.01057472, 0.00258121,
        0.001437  , 0.0020514 , 0.00411515, 0.00140319, 0.00131574,
        0.00170465, 0.00382147, 0.00139656, 0.00193329, 0.00264182,
        0.00752368]),
 'std_score_time': array([1.08618566e-03, 3.29391757e-03, 3.06021709e-03, 6.01486305e-03,
        1.20834501e-03, 7.83673419e-05, 6.87253537e-

In [22]:
pa2 = {
    'C':[ 0.1, 1,10,100],
    'kernel': ['linear', 'poly', 'rbf', 'sigmoid']
}



In [23]:
clf2 = RandomizedSearchCV(model, pa2, cv=5)

In [24]:
clf2.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(),
                   param_distributions={'C': [0.1, 1, 10, 100],
                                        'kernel': ['linear', 'poly', 'rbf',
                                                   'sigmoid']})

In [25]:
clf2.best_params_

{'kernel': 'linear', 'C': 100}

In [26]:
clf2.best_score_

np.float64(0.9631268436578171)

In [27]:
clf2.cv_results_

{'mean_fit_time': array([4.64128637e+00, 1.14619732e-02, 4.41002846e-03, 6.14724159e-03,
        4.10246849e-03, 1.54149055e-02, 1.15575903e+01, 1.36484580e+00,
        4.13160324e-03, 5.24568558e-03]),
 'std_fit_time': array([9.07199129e-01, 3.66668782e-03, 2.29616625e-04, 1.64382070e-04,
        1.32760748e-04, 5.78221169e-04, 3.10386216e+00, 5.29406168e-01,
        1.27050163e-04, 1.01676425e-03]),
 'mean_score_time': array([0.00138206, 0.00321245, 0.00158119, 0.00259104, 0.00173483,
        0.00431767, 0.00143342, 0.00128355, 0.00147266, 0.0019599 ]),
 'std_score_time': array([1.94309322e-04, 7.94915832e-04, 4.97643031e-05, 8.09679604e-05,
        5.15764140e-05, 2.75473849e-04, 2.42598251e-04, 5.49651994e-05,
        1.11536217e-04, 3.22428232e-04]),
 'param_kernel': masked_array(data=['linear', 'sigmoid', 'rbf', 'rbf', 'rbf', 'sigmoid',
                    'linear', 'linear', 'poly', 'poly'],
              mask=[False, False, False, False, False, False, False, False,
            